Check error code for requirements install

diff --git a/requirements b/requirements
--- a/requirements
+++ b/requirements
@@ -6,5 +6,10 @@ pushd `pwd`
 cd $THIS_DIR/codalab/requirements
 ARGS=""
 for a in $@; do ARGS="$ARGS -r $a"; done
-pip install $ARGS 
+pip install $ARGS
+rc=$?
+if [[ $rc != 0 ]] ; then
+  echo "*** There was an error installing requirements"
+  exit $rc
+fi
 popd
